# Generated by Django 5.1.3 on 2025-01-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0013_alter_match_round'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='ligameet.sportprofile'),
        ),
    ]
