# Generated by Django 5.1.3 on 2024-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligameet', '0012_alter_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('First Round', 'First Round'), ('Quarter-finals', 'Quarter-finals'), ('Semi-finals', 'Semi-finals'), ('Finals', 'Finals'), ('Grand finals', 'Grand finals')], max_length=50, null=True),
        ),
    ]
